name: Deploy OCI Instance Creator to Docker and OCI
on:
  push:
    branches: ['*']
  pull_request:

jobs:
  dist:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Login en Docker Hub usando SECRETS
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Build y Push
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

      # 3. Despliegue en OCI usando SECRETS para auth y VARS para config
      - name: Launch OCI Instance
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: |
            compute instance launch \
              --availability-domain "${{ vars.OCI_AVAILABILITY_DOMAIN }}" \
              --compartment-id "${{ secrets.OCI_TENANCY_OCID }}" \
              --shape "VM.Standard.A1.Flex" \
              --shape-config '{"ocpus": ${{ vars.OCI_OCPUS }}, "memoryInGBs": ${{ vars.OCI_MEMORY_IN_GBS }}}' \
              --subnet-id "${{ vars.OCI_SUBNET_ID }}" \
              --image-id "${{ vars.OCI_IMAGE_ID }}" \
              --display-name "OCI-Instance-from-Github" \
              --assign-public-ip true
        env:
          OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY_CONTENTS }}
          OCI_CLI_REGION: us-sanjose-1
